version: "3.3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev123
      MYSQL_PASSWORD: dev123

  app:
    depends_on:
      - db
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '8081:8081'

volumes:
  db_data: {}
